name: Linting (Prettier & ESLint & Commitlint)

on: pull_request

jobs:
  prettier:
    name: Prettier Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/hydrogen'

      - run: pnpm install --frozen-lockfile

      - run: pnpm run lint:prettier:check

  eslint:
    name: ESLint Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/hydrogen'

      - run: pnpm install --frozen-lockfile

      - run: pnpm run lint:eslint:check

  commitlint:
    name: Commitlint Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/hydrogen'

      - run: pnpm install --frozen-lockfile

      - name: Validate PR commits with commitlint
        run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose