name: Automated Tests

on: pull_request

jobs:
  jest:
    name: Run Jest Tests on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/hydrogen'

      - run: pnpm install --frozen-lockfile

      - run: pnpm run test